-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXmPfSldk1WgSIy1k
VDAqolAkMTnSBHnRz9afWxpWbx+gCgYIKoZIzj0DAQehRANCAAT7a8RS2okdq+Mg
ag6E+wXiHESLH/z/I/mAGAU1CHipAEdvqUKePx4qMuurCAgL5lnj9aTOGcd8UCJ9
/WUdXoVP
-----END PRIVATE KEY-----